[package]
name = "knot"
version = "0.1.0"
authors = ["Andrew Vy <andrew@andrewvy.com>"]

[dependencies]
bytes = "0.4.6"
clap = "2.31.1"
failure = "0.1.1"
failure_derive = "0.1.1"
futures = "0.1.18"
tokio = "0.1.3"
tokio-io = "0.1.6"
